Add training position assignments
VATSIM-UK/ukts-core-api pull request #36
Opened 2020-01-08 19:00 UTC by AxonC

Closes #22.

- Adds the ability to mark & unmark positions as available for training
- Adds ability to query these positions

2020-01-12 20:03 UTC, AndyTWF requested changes
Mostly just questions

2020-01-12 20:03 UTC, AndyTWF commented on app/Modules/Position/PositionNotAssignedForTrainingException.php
> +            'code' => 422,
This code should probably be 404.

2020-01-12 20:03 UTC, AndyTWF commented on database/migrations/2020_01_07_200042_create_training_position_assignments_table.php
> +            $table->unsignedBigInteger('position_id');
Foreign key here?

2020-01-12 21:11 UTC, AxonC commented on database/migrations/2020_01_07_200042_create_training_position_assignments_table.php
> +            $table->unsignedBigInteger('position_id');
added :)

2020-01-12 21:11 UTC, AxonC commented on app/Modules/Position/PositionNotAssignedForTrainingException.php
> +            'code' => 422,
good catch!

2020-01-15 21:37 UTC, AndyTWF approved these changes

2020-01-15 21:38 UTC, merged